# Generated by Django 3.2.6 on 2021-08-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epapp', '0004_auto_20210808_0044'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='enrol',
            new_name='enroll',
        ),
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
