# Generated by Django 3.2.6 on 2021-08-08 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('epapp', '0005_auto_20210808_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=90)),
                ('topic', models.CharField(max_length=90)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epapp.course')),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=150)),
                ('op1', models.CharField(max_length=150)),
                ('op2', models.CharField(max_length=150)),
                ('op3', models.CharField(max_length=150)),
                ('op4', models.CharField(max_length=150)),
                ('correct', models.IntegerField()),
                ('points', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epapp.coursequiz')),
            ],
        ),
        migrations.RemoveField(
            model_name='courseassignment',
            name='deadline',
        ),
        migrations.CreateModel(
            name='CourseQuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epapp.coursequiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CourseQuizResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected', models.IntegerField()),
                ('quizquestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='epapp.coursequizquestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
